# Generated by Django 3.2.5 on 2021-07-22 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agregado_Paciente_Exame_Amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_realizacao', models.DateTimeField(auto_now_add=True)),
                ('data_de_solicitacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_amostra', models.CharField(max_length=255)),
                ('metodo_de_coleta', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('virus', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('nascimento', models.DateField(verbose_name='data de nascimento')),
            ],
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('cpf',), name='unique_paciente'),
        ),
        migrations.AddField(
            model_name='exame',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ep3.paciente'),
        ),
        migrations.AddConstraint(
            model_name='amostra',
            constraint=models.UniqueConstraint(fields=('codigo_amostra',), name='unique_amostra'),
        ),
        migrations.AddField(
            model_name='agregado_paciente_exame_amostra',
            name='amostra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ep3.amostra'),
        ),
        migrations.AddField(
            model_name='agregado_paciente_exame_amostra',
            name='exame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ep3.exame'),
        ),
        migrations.AddField(
            model_name='agregado_paciente_exame_amostra',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ep3.paciente'),
        ),
        migrations.AddConstraint(
            model_name='exame',
            constraint=models.UniqueConstraint(fields=('tipo', 'virus'), name='unique_exame'),
        ),
        migrations.AddConstraint(
            model_name='agregado_paciente_exame_amostra',
            constraint=models.UniqueConstraint(fields=('paciente', 'exame', 'amostra', 'data_de_realizacao'), name='unique_agregado'),
        ),
    ]
