# Generated by Django 3.2.5 on 2021-07-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep3', '0004_auto_20210722_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exame',
            old_name='id_paciente',
            new_name='paciente',
        ),
        migrations.AlterField(
            model_name='agregado_paciente_exame_amostra',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ep3.paciente'),
        ),
    ]
