# Generated by Django 3.2.5 on 2021-07-22 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ep3', '0008_remove_agregado_paciente_exame_amostra_data_de_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agregado_paciente_exame_amostra',
            name='data_de_solicitacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
