# Generated by Django 3.2.5 on 2021-07-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ep3', '0012_alter_agregado_paciente_exame_amostra_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amostra',
            name='exame',
        ),
    ]
