# Generated by Django 3.2.5 on 2021-07-22 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep3', '0013_remove_amostra_exame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregado_paciente_exame_amostra',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ep3.paciente'),
        ),
    ]
