# Generated by Django 3.2.5 on 2021-07-22 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep3', '0015_exame_amostra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregado_paciente_exame_amostra',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ep3.paciente'),
        ),
    ]
