# Generated by Django 3.2.5 on 2021-07-22 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep3', '0016_alter_agregado_paciente_exame_amostra_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='amostra',
        ),
        migrations.AddField(
            model_name='amostra',
            name='exame',
            field=models.ManyToManyField(through='ep3.Agregado_Paciente_Exame_Amostra', to='ep3.Exame'),
        ),
        migrations.AlterField(
            model_name='agregado_paciente_exame_amostra',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ep3.paciente'),
        ),
    ]
