# Generated by Django 3.2.5 on 2021-07-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep3', '0017_auto_20210722_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='amostra',
            name='paciente',
            field=models.ManyToManyField(through='ep3.Agregado_Paciente_Exame_Amostra', to='ep3.Paciente'),
        ),
    ]
