# Generated by Django 3.2.5 on 2021-07-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep3', '0019_auto_20210722_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='amostra',
            name='exame',
            field=models.ManyToManyField(through='ep3.Agregado_Paciente_Exame_Amostra', to='ep3.Exame'),
        ),
    ]
