# Generated by Django 3.2.5 on 2021-07-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ep3', '0020_amostra_exame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amostra',
            name='exame',
        ),
    ]
