# Generated by Django 3.2.5 on 2021-07-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep3', '0021_remove_amostra_exame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregado_paciente_exame_amostra',
            name='exame',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ep3.exame'),
        ),
    ]
