# Generated by Django 3.2.5 on 2021-07-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep3', '0022_alter_agregado_paciente_exame_amostra_exame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='paciente',
        ),
        migrations.AddField(
            model_name='exame',
            name='paciente',
            field=models.ManyToManyField(through='ep3.Agregado_Paciente_Exame_Amostra', to='ep3.Paciente'),
        ),
    ]
