# Generated by Django 3.2.5 on 2021-07-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep3', '0023_auto_20210723_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='paciente',
        ),
        migrations.AddField(
            model_name='exame',
            name='paciente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='ep3.paciente'),
        ),
    ]
